version: '3.8'

volumes: 
  db-data:

services:
  frontend:
    build: ./frontend
    ports:
      - '8080:3000'
    volumes:
      - './frontend:/app'
    command: yarn run dev
    depends_on:
      - web-bff

  web-bff:
    build: ./web-bff
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    ports:
      - '3000:3000'
    volumes:
      - './web-bff:/web-bff'
    tty: true
    stdin_open: true
    # dbのサービスを先に起動するようにdepends_onで指定
    depends_on:
      - db
    # dbのサービスにアクセスできるようlinksで指定
    links:
      - db

  auth-api:
    build: ./auth-api
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    ports:
      - '3011:3000'
    volumes:
      - './auth-api:/auth-api'
    tty: true
    stdin_open: true
    # dbのサービスを先に起動するようにdepends_onで指定
    depends_on:
      - db
    # dbのサービスにアクセスできるようlinksで指定
    links:
      - db

  task-api:
    build: ./task-api
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    ports:
      - '3012:3000'
    volumes:
      - './task-api:/task-api'
    tty: true
    stdin_open: true
    # dbのサービスを先に起動するようにdepends_onで指定
    depends_on:
      - db
    # dbのサービスにアクセスできるようlinksで指定
    links:
      - db

  db:
    image: postgres
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      # POSTGRES_PASSWORD: 'postgres'
    # volumeを指定しホスト側とデータを共有しておく（コンテナ内で保存したものは揮発するため、ホスト側に保存しておくと残せる）
    volumes:
      # コンテナのpostgresのデータ保存先
      - 'db-data:/var/lib/postgresql/data'